swagger: "2.0"
info:
  title: Inventory Service - Data Models - REST API
  description: |
    REST API for Inventory Service
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths: {}
definitions:
  Supplier:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  CompanyOwner:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Department:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Project:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  DeviceState:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  DeviceType:
    type: object
    properties:
      id:
        type: integer
        format: int64
      objectTypeName:
        type: string
      classification:
        type: integer
      manufacturer:
        type: string
      orderNumber:
        type: string
      version:
        type: string
      supplier:
        $ref: '#/definitions/Supplier'
      price:
        type: number
        format: double
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      superiorFirstName:
        type: string
      superiorLastName:
        type: string
      flagRead:
        type: boolean
      flagWrite:
        type: boolean
      flagBorrow:
        type: boolean
      flagInventory:
        type: boolean
      flagRevision:
        type: boolean
      flagAdmin:
        type: boolean
  DeviceRevision:
    type: object
    properties:
      id:
        type: integer
        format: int64
      revisionInterval:
        type: integer
      lastRevisionDateString:
        type: string
  DeviceCalibration:
    type: object
    properties:
      id:
        type: integer
        format: int64
      calibrationInterval:
        type: integer
      lastCalibrationDateString:
        type: string
  Device:
    type: object
    properties:
      id:
        type: integer
        format: int64
      addDateString:
        type: string
      barcodeNumber:
        type: string
      calibration:
        $ref: '#/definitions/DeviceCalibration'
      comment:
        type: string
      companyOwner:
        $ref: '#/definitions/CompanyOwner'
      defaultLocation:
        type: string
      department:
        $ref: '#/definitions/Department'
      deviceState:
        $ref: '#/definitions/DeviceState'
      deviceType:
        $ref: '#/definitions/DeviceType'
      project:
        $ref: '#/definitions/Project'
      revision:
        $ref: '#/definitions/DeviceRevision'
      inventoryRecord:
        $ref: '#/definitions/InventoryRecord'
      serialNumber:
        type: string
      holder:
        $ref: '#/definitions/User'
      owner:
        $ref: '#/definitions/User'
  InventoryRecord:
    type: object
    properties:
      id:
        type: integer
        format: int64
      inventoryState:
        $ref: '#/definitions/InventoryState'
  InventoryState:
    type: string
    enum:
      - 'OK'
      - 'False'
      - 'Unclear'