swagger: "2.0"
info:
  title: Inventory Service - Data Models - REST API
  description: |
    REST API for Inventory Service
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths: {}
definitions:
  Supplier:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  CompanyOwner:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Department:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Project:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  DeviceState:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  DeviceType:
    type: object
    properties:
      id:
        type: integer
        format: int64
      objectTypeName:
        type: string
      classification:
        type: integer
      manufacturer:
        type: string
      orderNumber:
        type: string
      version:
        type: string
      supplier:
        $ref: '#/definitions/Supplier'
      price:
        type: number
        format: double
  Device:
    type: object
    properties:
      id:
        type: integer
        format: int64
      addDate:
        type: string
        format: date-time
      barcodeNumber:
        type: string
      comment:
        type: string
      companyOwner:
        $ref: '#/definitions/CompanyOwner'
      defaultLocation:
        type: string
      department:
        $ref: '#/definitions/Department'
      deviceState:
        $ref: '#/definitions/DeviceState'
      deviceType:
        $ref: '#/definitions/DeviceType'
      project:
        $ref: '#/definitions/Project'
      serialNumber:
        type: string
      #todo holder
      #todo owner