swagger: "2.0"
info:
  title: Siemens Inventory REST API
  description: |
    REST API for Inventory Service
  version: 1.0.0
schemes:
  - https
basePath: /inventory-service/api/v1
produces:
  - application/json
paths:
  /devices:
    get:
      tags:
        - Device
      summary: Gets all Devices
      operationId: getDevices
      produces:
        - application/json
      responses:
        '200':
          description: All Devices
          schema:
            type: array
            items:
              $ref: './common-models.yaml#/definitions/Device'
        '405':
          description: Invalid input
    post:
      tags:
        - Device
      summary: Creates new Device
      operationId: createDevice
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Device object that needs to be created
          required: true
          schema:
            $ref: './common-models.yaml#/definitions/Device'
      responses:
        '201':
          description: Device created
          schema:
            $ref: './common-models.yaml#/definitions/Device'
        '405':
          description: Invalid input
  /devices/{deviceId}:
    get:
      tags:
        - Device
      summary: Gets Device based on deviceId
      operationId: getDevice
      produces:
        - application/json
      parameters:
        - name: deviceId
          in: path
          description: Device id to get
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: The device
          schema:
            $ref: './common-models.yaml#/definitions/Device'
        '404':
          description: Requested device does not exist.
    put:
      tags:
        - Device
      summary: Updates Device based on deviceId
      operationId: updateDevice
      produces:
        - application/json
      parameters:
        - name: deviceId
          in: path
          description: Device id to update
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Device that needs to be updated
          required: true
          schema:
            $ref: './common-models.yaml#/definitions/Device'
      responses:
        '201':
          description: Device created
          schema:
            $ref: './common-models.yaml#/definitions/Device'
        '404':
          description: Device not found
    delete:
      tags:
        - Device
      summary: Deletes an device
      description: ''
      operationId: deleteDevice
      produces:
        - application/json
      parameters:
        - name: deviceId
          in: path
          description: Device id to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Device was deleted.
        '404':
          description: Specified device does not exist.
  /devices/barcodeNumber/{barcodeNumber}:
    get:
      tags:
        - Device
      summary: Gets Device based on barcodeNumber
      operationId: getDeviceWithBarcodeNumber
      produces:
        - application/json
      parameters:
        - name: barcodeNumber
          in: path
          description: barcodeNumber of device
          required: true
          type: string
      responses:
        '200':
          description: The device
          schema:
            $ref: './common-models.yaml#/definitions/Device'
        '404':
          description: Requested device does not exist.
  /devices/serialNumber/{serialNumber}:
    get:
      tags:
        - Device
      summary: Gets Device based on serialNumber
      operationId: getDeviceWithSerialNumber
      produces:
        - application/json
      parameters:
        - name: serialNumber
          in: path
          description: serialNumber of device
          required: true
          type: string
      responses:
        '200':
          description: The device
          schema:
            $ref: './common-models.yaml#/definitions/Device'
        '404':
          description: Requested device does not exist.
  /devices/serialNumber/like/{serialNumber}:
    get:
      tags:
        - Device
      summary: Gets Devices based on serialNumber like
      operationId: getDevicesWithSerialNumberLike
      produces:
        - application/json
      parameters:
        - name: serialNumber
          in: path
          description: serialNumber of device
          required: true
          type: string
      responses:
        '200':
          description: Devices with serial number like
          schema:
            type: array
            items:
              $ref: './common-models.yaml#/definitions/Device'
  /devices/borrowed-by/{userScdId}:
    get:
      tags:
        - Device
      summary: Gets Devices borrowed by userScdId
      operationId: getDevicesBorrowedBy
      produces:
        - application/json
      parameters:
        - name: userScdId
          in: path
          description: User
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Devices borrowed by userScdId
          schema:
            type: array
            items:
              $ref: './common-models.yaml#/definitions/Device'