swagger: "2.0"
info:
  title: Inventory Service - DeviceInternal State - REST API
  description: |
    REST API for Inventory Service
  version: 1.0.0
schemes:
  - https
basePath: /inventory-service/api/v1
produces:
  - application/json
paths:
  /device-states:
    get:
      tags:
        - DeviceState
      summary: Gets all DeviceInternal States
      operationId: getDeviceStates
      produces:
        - application/json
      responses:
        '200':
          description: All DeviceInternal States
          schema:
            type: array
            items:
              $ref: './common-models.yaml#/definitions/DeviceState'
    post:
      tags:
        - DeviceState
      summary: Creates new DeviceInternal State
      operationId: createDeviceState
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: DeviceInternal State object that needs to be created
          required: true
          schema:
            $ref: './common-models.yaml#/definitions/DeviceState'
      responses:
        '201':
          description: DeviceInternal State created
          schema:
            $ref: './common-models.yaml#/definitions/DeviceState'
        '405':
          description: Invalid input
  /device-states/{deviceStateId}:
    get:
      tags:
        - DeviceState
      summary: Gets DeviceInternal State based on deviceStateId
      operationId: getDeviceState
      produces:
        - application/json
      parameters:
        - name: deviceStateId
          in: path
          description: DeviceInternal State's id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: The DeviceInternal State
          schema:
            $ref: './common-models.yaml#/definitions/DeviceState'
        '404':
          description: Requested DeviceInternal State does not exist.
    delete:
      tags:
        - DeviceState
      summary: Deletes an DeviceInternal State
      operationId: deleteDeviceState
      produces:
        - application/json
      parameters:
        - name: deviceStateId
          in: path
          description: DeviceInternal State's id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: DeviceInternal State was deleted.
        '404':
          description: Specified DeviceInternal State does not exist.