swagger: "2.0"
info:
  title: Siemens Inventory REST API
  description: |
    REST API for Siemens Inventory
  version: 1.0.0
schemes:
  - https
basePath: /inventory/api/v1
produces:
  - application/json
paths:
  /device-type:
    get:
      tags:
        - DeviceType
      summary: Gets all Device types
      operationId: getDeviceTypess
      produces:
        - application/json
      responses:
        '200':
          description: All Device Types
        '405':
          description: Invalid input