swagger: "2.0"
info:
  title: Inventory Service - Calibration - REST API
  description: |
    REST API for Inventory Service
  version: 1.0.0
schemes:
  - https
basePath: /inventory-service/api/v1
produces:
  - application/json
paths:
  /calibrations:
    post:
      tags:
        - Calibration
      summary: Creates new Calibration
      operationId: createCalibration
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Calibration object that needs to be created
          required: true
          schema:
            $ref: './common-models.yaml#/definitions/DeviceCalibration'
      responses:
        '201':
          description: Calibration created
          schema:
            $ref: './common-models.yaml#/definitions/DeviceCalibration'
        '405':
          description: Invalid input
  /calibrations/{calibrationId}:
    get:
      tags:
        - Calibration
      summary: Gets Calibration based on calibrationId
      operationId: getCalibration
      produces:
        - application/json
      parameters:
        - name: calibrationId
          in: path
          description: Calibration's id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: The Calibration
          schema:
            $ref: './common-models.yaml#/definitions/DeviceCalibration'
        '404':
          description: Requested Calibration does not exist.
    put:
      tags:
        - Calibration
      summary: Updates an Calibration based on revisionId
      operationId: updateCalibration
      produces:
        - application/json
      parameters:
        - name: calibrationId
          in: path
          description: Calibration id to update
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Calibration object that needs to be updated
          required: true
          schema:
            $ref: './common-models.yaml#/definitions/DeviceCalibration'
      responses:
        '200':
          description: Updated Calibration
          schema:
            $ref: './common-models.yaml#/definitions/DeviceCalibration'
        '404':
          description: Specified Calibration does not exist.