swagger: "2.0"
info:
  title: Inventory Service - Project - REST API
  description: |
    REST API for Inventory Service
  version: 1.0.0
schemes:
  - https
basePath: /inventory-service/api/v1
produces:
  - application/json
paths:
  /projects:
    get:
      tags:
        - Project
      summary: Gets all Projects
      operationId: getProjects
      produces:
        - application/json
      responses:
        '200':
          description: All Projects
          schema:
            type: array
            items:
              $ref: './common-models.yaml#/definitions/Project'
    post:
      tags:
        - Project
      summary: Creates new Project
      operationId: createProject
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Project object that needs to be created
          required: true
          schema:
            $ref: './common-models.yaml#/definitions/Project'
      responses:
        '201':
          description: Project created
          schema:
            $ref: './common-models.yaml#/definitions/Project'
        '405':
          description: Invalid input
  /projects/{projectId}:
    get:
      tags:
        - Project
      summary: Gets Project based on projectId
      operationId: getProject
      produces:
        - application/json
      parameters:
        - name: projectId
          in: path
          description: Project's id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: The Project
          schema:
            $ref: './common-models.yaml#/definitions/Project'
        '404':
          description: Requested Project does not exist.
    put:
      tags:
        - Project
      summary: Updates Project based on projectId
      operationId: updateProject
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: projectId
          in: path
          description: Project's id
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Project object that needs to be updated
          required: true
          schema:
            $ref: './common-models.yaml#/definitions/Project'
      responses:
        '200':
          description: The Project
          schema:
            $ref: './common-models.yaml#/definitions/Project'
        '404':
          description: Requested Project does not exist.
    delete:
      tags:
        - Project
      summary: Deletes an Project
      operationId: deleteProject
      produces:
        - application/json
      parameters:
        - name: projectId
          in: path
          description: Project's id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Project was deleted.
        '404':
          description: Specified Project does not exist.